apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-rroo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-rroo
    app.kubernetes.io/part-of: load-app-236b01c3-c31e-4488-818d-64d43c0fbed0
  name: devfile-sample-rroo
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-rroo
status:
  loadBalancer: {}
